#!/bin/bash
export VOLUMES=${1:-localhost:3001}      # volume server variable
export DB=${2:-/tmp/cachedb/}            # database
export TYPE=master                       # type var
uwsgi --http :${PORT:-3000} --wsgi-file src/server.py --callable master  --master --processes 4
